title: Lucy Lin
logo: /assets/img/headshot_circle.png
description: ğŸ‘©â€ğŸ’» Data Scientist with hands-on experience in machine learning, NLP, and data-driven product development. Passionate about solving real-world problems with scalable, intelligent systems.
#show_downloads: true
theme: jekyll-theme-minimal
